name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: | 
            echo "Ok, bye honey"
            echo "Where is my beer honey?"
            pwd
            ls
